python src/main.py mtable train \
    --model src/cfg/models/startsr-mtable.yaml \
    --data src/cfg/datasets/TG24K.yaml \
    --epochs 200 \
    --device 0,1 \
    --master_batch -1 \
    --batch 38 \
    --workers 32 \
    --lr_step 140,180 \
    --val_epochs 10 \
    --project Train/TG24K \
    --name star