dirs: # Directory configuration
  data_dir: "datasets" # Training data catalog
  runs_dir: "runs" # Experiment directory, if not set, project and name parameters, the experiment will be saved to the runs directory
  