python src/main.py mtable train \
    --model src/cfg/models/dlatsr-mtable.yaml \
    --data src/cfg/datasets/WTW.yaml \
    --epochs 200 \
    --device 0,1 \
    --master_batch -1 \
    --batch 22 \
    --workers 32 \
    --lr_step 140,180 \
    --val_epochs 10 \
    --project Train/WTW \
    --name dla